modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    modId="newposts"
    version="${file.jarVersion}"
    displayName="Newposts"
    description='''디시인사이드 새글 알리미'''
    logoFile="icon.png"
    authors="Teashoe"

[[dependencies.newposts]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.newposts]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
